services:
  sobel:
    image: picklerick65/sobel-dev:latest
    container_name: sobel-latest
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    working_dir: /workspace
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --no-browser
      --ServerApp.token=''
      --ServerApp.password=''
    tty: true